sonar.projectKey=Haiyahhh_kubernetes-goat
sonar.organization=haiyahhh

sonar.sources=.
sonar.exclusions=**/node_modules/**, **/vendor/**, **/*.md, guide/**, images/**, .github/**, **/go.sum, **/go.mod

sonar.sourceEncoding=UTF-8