apiVersion: v1
kind: Secret
metadata:
  name: goatvault
  namespace: default
type: Opaque
data:
  k8sgoatvaultkey: azhzLWdvYXQtY2QyZGEyNzIyNDU5MWRhMmI0OGVmODM4MjZhOGE2YzM=

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: system-monitor-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: system-monitor
  template:
    metadata:
      labels:
        app: system-monitor
    spec:
      # ==========================================
      # REMEDIATION: Section 5.2 (host namespace sharing)
      # Remove host namespace sharing
      # ==========================================
      hostPID: false
      hostIPC: false
      #hostNetwork: true

      # ==========================================
      # REMEDIATION: Section 5.2 (overly permissive hostPath mount)
      # Removed the mount targeting '/''
      # ==========================================
      # volumes:
      # - name: host-filesystem
      #   hostPath:
      #     path: /
      
      containers:
      - name: system-monitor
        image: secure-system-monitor:v1
        resources:
          limits:
            memory: "50Mi"
            cpu: "20m"
        securityContext:
          # ==========================================
          # REMEDIATION: Section 5.2 (privilege escalation)
          # Prevent privilege escalation
          # ==========================================
          allowPrivilegeEscalation: false
          privileged: false
          runAsNonRoot: true
        ports:
        - containerPort: 8080
        
        # ==========================================
        # REMEDIATION: Section 5.2 (Overly privilege mount)
        # Remove the volumnMount targeting /host-system
        # ==========================================
        # volumeMounts:
        # - name: host-filesystem
        #   mountPath: /host-system
        env:
          - name: K8S_GOAT_VAULT_KEY
            valueFrom:
              secretKeyRef:
                name: goatvault
                key: k8sgoatvaultkey
---
apiVersion: v1
kind: Service
metadata:
  name: system-monitor-service
  namespace: default
spec:
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: system-monitor
